"use client";

import DashboardLayout from "@/components/dashboard-layout";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Loader, AlertCircle, CheckCircle2, ArrowLeft } from "lucide-react";

export default function AdmissionsPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const [classes, setClasses] = useState([]);
  const [classesLoading, setClassesLoading] = useState(true);

  const [formData, setFormData] = useState({
    first_name: '',
    last_name: '',
    middle_name: '',
    gender: '',
    date_of_birth: '',
    class_id: '',
    stream_id: '',
    guardian_name: '',
    guardian_phone: '',
    guardian_email: '',
    address: '',
    admission_number: '',
  });

  // Fetch classes on mount
  React.useEffect(() => {
    fetchClasses();
  }, []);

  const fetchClasses = async () => {
    try {
      const response = await fetch('/api/modules/hr/classes?limit=100');
      if (!response.ok) throw new Error('Failed to fetch classes');
      const data = await response.json();
      setClasses(data.data || []);
    } catch (err) {
      console.error('Fetch classes error:', err);
    } finally {
      setClassesLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSelectChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      // Validate required fields
      if (!formData.first_name || !formData.last_name || !formData.gender || !formData.date_of_birth) {
        throw new Error('Please fill in all required fields (First Name, Last Name, Gender, Date of Birth)');
      }

      // Prepare data for admission
      const admissionData = {
        first_name: formData.first_name.trim(),
        last_name: formData.last_name.trim(),
        middle_name: formData.middle_name.trim() || null,
        gender: formData.gender,
        date_of_birth: formData.date_of_birth,
        class_id: formData.class_id ? parseInt(formData.class_id) : null,
        stream_id: formData.stream_id ? parseInt(formData.stream_id) : null,
        guardian_name: formData.guardian_name.trim() || null,
        guardian_phone: formData.guardian_phone.trim() || null,
        guardian_email: formData.guardian_email.trim() || null,
        address: formData.address.trim() || null,
        // admission_number is auto-generated by API if not provided
        ...(formData.admission_number && { admission_number: formData.admission_number.trim() }),
      };

      const response = await fetch('/api/modules/students/admissions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(admissionData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || `HTTP ${response.status}: ${response.statusText}`);
      }

      if (!data.success) {
        throw new Error(data.error || 'Failed to admit student');
      }

      setSuccess(true);
      
      // Redirect to students page after 2 seconds
      setTimeout(() => {
        router.push('/students');
      }, 2000);

    } catch (err) {
      setError(err.message || 'An error occurred while admitting the student');
      console.error('Admission error:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-6">
        {/* Header */}
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            size="icon"
            onClick={() => router.back()}
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div>
            <h1 className="text-3xl font-bold">Student Admission</h1>
            <p className="text-gray-600">Register a new student to the school</p>
          </div>
        </div>

        {/* Error Alert */}
        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Success Alert */}
        {success && (
          <Alert className="bg-green-50 border-green-200">
            <CheckCircle2 className="h-4 w-4 text-green-600" />
            <AlertTitle className="text-green-800">Success</AlertTitle>
            <AlertDescription className="text-green-700">
              Student admitted successfully! Redirecting to students list...
            </AlertDescription>
          </Alert>
        )}

        {/* Form Card */}
        <Card>
          <CardHeader>
            <CardTitle>Student Information</CardTitle>
            <CardDescription>Fill in the student's details. Fields marked with * are required.</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Personal Information */}
              <div className="space-y-4">
                <h3 className="font-semibold text-lg">Personal Information</h3>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="first_name">First Name *</Label>
                    <Input
                      id="first_name"
                      name="first_name"
                      placeholder="John"
                      value={formData.first_name}
                      onChange={handleInputChange}
                      required
                      disabled={loading}
                    />
                  </div>
                  <div>
                    <Label htmlFor="last_name">Last Name *</Label>
                    <Input
                      id="last_name"
                      name="last_name"
                      placeholder="Doe"
                      value={formData.last_name}
                      onChange={handleInputChange}
                      required
                      disabled={loading}
                    />
                  </div>
                </div>

                <div>
                  <Label htmlFor="middle_name">Middle Name</Label>
                  <Input
                    id="middle_name"
                    name="middle_name"
                    placeholder="Optional"
                    value={formData.middle_name}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="gender">Gender *</Label>
                    <Select value={formData.gender} onValueChange={(value) => handleSelectChange('gender', value)}>
                      <SelectTrigger id="gender" disabled={loading}>
                        <SelectValue placeholder="Select gender" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="male">Male</SelectItem>
                        <SelectItem value="female">Female</SelectItem>
                        <SelectItem value="other">Other</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="date_of_birth">Date of Birth *</Label>
                    <Input
                      id="date_of_birth"
                      name="date_of_birth"
                      type="date"
                      value={formData.date_of_birth}
                      onChange={handleInputChange}
                      required
                      disabled={loading}
                    />
                  </div>
                </div>
              </div>

              {/* School Information */}
              <div className="space-y-4 border-t pt-6">
                <h3 className="font-semibold text-lg">School Information</h3>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="class_id">Class / Level</Label>
                    <Select value={formData.class_id} onValueChange={(value) => handleSelectChange('class_id', value)}>
                      <SelectTrigger id="class_id" disabled={loading || classesLoading}>
                        <SelectValue placeholder={classesLoading ? "Loading classes..." : "Select class"} />
                      </SelectTrigger>
                      <SelectContent>
                        {classes.map((cls) => (
                          <SelectItem key={cls.id} value={cls.id.toString()}>
                            {cls.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="stream_id">Stream (Optional)</Label>
                    <Input
                      id="stream_id"
                      name="stream_id"
                      placeholder="e.g., A, B, C"
                      value={formData.stream_id}
                      onChange={handleInputChange}
                      disabled={loading}
                    />
                  </div>
                </div>

                <div>
                  <Label htmlFor="admission_number">Admission Number (Auto-generated if blank)</Label>
                  <Input
                    id="admission_number"
                    name="admission_number"
                    placeholder="Leave blank for auto-generation"
                    value={formData.admission_number}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Guardian Information */}
              <div className="space-y-4 border-t pt-6">
                <h3 className="font-semibold text-lg">Guardian Information</h3>

                <div>
                  <Label htmlFor="guardian_name">Guardian Name</Label>
                  <Input
                    id="guardian_name"
                    name="guardian_name"
                    placeholder="Parent or guardian's name"
                    value={formData.guardian_name}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="guardian_phone">Guardian Phone</Label>
                    <Input
                      id="guardian_phone"
                      name="guardian_phone"
                      placeholder="+1 (555) 000-0000"
                      type="tel"
                      value={formData.guardian_phone}
                      onChange={handleInputChange}
                      disabled={loading}
                    />
                  </div>
                  <div>
                    <Label htmlFor="guardian_email">Guardian Email</Label>
                    <Input
                      id="guardian_email"
                      name="guardian_email"
                      placeholder="guardian@example.com"
                      type="email"
                      value={formData.guardian_email}
                      onChange={handleInputChange}
                      disabled={loading}
                    />
                  </div>
                </div>
              </div>

              {/* Address */}
              <div className="space-y-4 border-t pt-6">
                <h3 className="font-semibold text-lg">Address</h3>
                <div>
                  <Label htmlFor="address">Residential Address</Label>
                  <Input
                    id="address"
                    name="address"
                    placeholder="123 Main Street, City, Country"
                    value={formData.address}
                    onChange={handleInputChange}
                    disabled={loading}
                  />
                </div>
              </div>

              {/* Actions */}
              <div className="flex gap-4 border-t pt-6">
                <Button
                  type="submit"
                  disabled={loading || success}
                  className="flex-1"
                >
                  {loading ? (
                    <>
                      <Loader className="h-4 w-4 mr-2 animate-spin" />
                      Admitting Student...
                    </>
                  ) : (
                    'Admit Student'
                  )}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => router.push('/students')}
                  disabled={loading}
                  className="flex-1"
                >
                  Cancel
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
